#ifndef COLORS_H
#define COLORS_H

enum ForegroundColors
{
    FOREGROUND_COLOR_BLACK =    30,
    FOREGROUND_COLOR_RED =      31,
    FOREGROUND_COLOR_GREEN =    32,
    FOREGROUND_COLOR_YELLOW =   33,
    FOREGROUND_COLOR_BLUE =     34,
    FOREGROUND_COLOR_MAGNETA =  35,
    FOREGROUND_COLOR_CYAN =     36,
    FOREGROUND_COLOR_WHITE =    37
};

enum BackgroundColors
{
    BACKGROUND_COLOR_BLACK =    40,
    BACKGROUND_COLOR_RED =      41,
    BACKGROUND_COLOR_GREEN =    42,
    BACKGROUND_COLOR_YELLOW =   43,
    BACKGROUND_COLOR_BLUE =     44,
    BACKGROUND_COLOR_MAGNETA =  45,
    BACKGROUND_COLOR_CYAN =     46,
    BACKGROUND_COLOR_WHITE =    47
};

#endif // COLORS_H
